config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
      :sessions => "users/sessions",
      :registrations => "users/registrations" }
  root to: "public#index"

  match 'admin/academic' => 'admin#academic', :via => :get
  match 'admin/pdf' => 'admin#pdf', :via => :get

  resources :users do
    member do
      get :delete
    end
  end

  resources :fixed_duration_programs do
    member do
      get :delete
    end
  end

  resources :insurances do
    member do
      get :update_insurance_cost
    end
  end

  resources :notes do
    member do
      get :delete
    end
  end

  resources :statements do
    member do
      get :delete
    end
  end

  resources :digital_tests do
    member do
      get :delete
    end
  end

  resources :admin do
    collection do
      get :academic
    end
    member do
      get :delete
    end
  end

  resources :payments do
    member do
      get :delete
    end
  end

  resources :invoices do
    member do
      get :load_config
      get :delete
    end
  end

  resources :agencies do
    member do
      get :delete
    end
  end

  resources :promos do
    member do
      get :delete
    end
  end

  resources :regions do

    member do
      get :delete
    end
  end

  resources :accommodations do
    member do
      get :delete
    end
  end

  resources :hours do
    member do
      get :delete
    end
  end
  
  resources :special_activities do
    member do
      get :delete
    end
  end
  
  resources :programs do
    member do
      get :delete
    end
  end
  
  resources :tests do
    member do
      get :delete
    end
  end
  
  resources :quizzes do
    member do
      get :delete
    end
  end
  
  resources :students do
    collection do
      post :import
      get :edit_multiple
      get :active
      get :student_list
      put :update_multiple
      patch :activate
      patch :deactivate
    end

    member do
      get :delete
    end

    resources :study_periods do
      member do
        get :letter_of_acceptance
        get :delete
      end
    end

    resources :quotes do
      member do
        get :load_config
        get :delete
      end
    end

    resources :pro_formas do
      member do
        get :load_config
        get :delete
      end
    end

    resources :invoices do
      member do
        get :delete
      end
    end
  end
  
  resources :attendances do
    member do
      get :delete
      patch :justify_absence
    end
  end
  
  resources :targets do
    member do
      get :delete
    end
  end
  
  resources :evaluations do
    member do
      get :report
      get :delete
      get :exercises
      get :daily
      get :regular
      put :set_evaluation_to_active
    end
  end

  resources :sharp_and_smarts do
    member do
      get :delete
    end
  end

  resources :automatizations do
    member do
      get :delete
    end
  end
  
  resources :items do
    member do
      get :delete
    end
  end

  
  resources :quotes, only: [:index]
  
  resources :pro_formas, only: [:index]
  
  resources :invoices, only: :index

  match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]

  match "/course/" => "public#language", via: :get, :as => :course_language

  match "/course/:language" => "public#group", via: :get, :as => :course_language_group

  match "/course/:language/group/:group" => "public#type", via: :get, :as => :course_language_group_type

  match "/course/:language/group/:group/type/attendances/" => "attendances#batch_edit", via: :get, :as => :course_language_group_type_attendances

  match "/course/:language/group/:group/type/targets/" => "targets#batch_edit", via: :get, :as => :course_language_group_type_targets

  match "/course/:language/group/:group/type/sharp_and_smarts/" => "sharp_and_smarts#batch_edit", via: :get, :as => :course_language_group_type_sharp_and_smarts

  match "/course/:language/group/:group/type/automatizations/" => "automatizations#batch_edit", via: :get, :as => :course_language_group_type_automatizations

end

app/models/target.rb
class Target < ActiveRecord::Base
  belongs_to :evaluation

  scope :newest_first, lambda { order("targets.created_at DESC" )}
  scope :newest_last, lambda { order("targets.created_at ASC" )}
  scope :between, -> (start_date, end_date) { where("created_at > ? AND created_at < ?", start_date, end_date) }

  validates_presence_of :date
  validates_presence_of :description
  validates_presence_of :letter_grade
  validates_presence_of :student_input
  validate :is_evaluation_active, :on => [:create, :update, :edit, :batch_edit]

  def is_evaluation_active
    unless evaluation.is_active?
      errors[:base] << 'The academic profile to which this attendance belongs must be active'
    end
  end
end

app/controllers/targets_controller.rb
class TargetsController < DailyController

  before_action :authenticate_user!
  before_action :find_evaluation

  def index
    if params[:evaluation_id]
      if params[:start_date].present? && params[:end_date].present?
        zone = 'Eastern Time (US & Canada)'
        start_date = ActiveSupport::TimeZone[zone].parse(params[:start_date]).utc
        end_date = ActiveSupport::TimeZone[zone].parse(params[:end_date]).end_of_day.utc
        @targets = @evaluation.targets.between(start_date, end_date)
      else
        @targets = @evaluation.targets.newest_first
      end
      @charted_targets = @targets
    else
      @targets = Target.newest_first
    end
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "targets.pdf",
               :template => "targets/index.pdf.erb",
               :layout => "pdf_layout.html",
               :page_size => "Letter",
               :orientation => 'Landscape',
               :javascript_delay => 3000,
               margin:  {   top:               5,                     # default 10 (mm)
                            bottom:            5,
                            left:              10,
                            right:             10 }
      end
    end
    authorize @targets
  end

  def create
    if params[:evaluation_id]
      @target = @evaluation.targets.new(target_params)
      @student = @evaluation.study_period.student
    else
      @target = Target.new(test_params)
    end
    authorize @target
    if @target.save
      respond_to do |format|
        format.html {redirect_to(:controller => :students, :action => :index)}
        format.js
      end
    else
      respond_to do |format|
        format.js {
          render 'targets/create'
        }
      end
    end
  end

  def edit
    @target = @evaluation.targets.find(params[:id])
    @student = @evaluation.study_period.student
    @detail_view = 1 if params[:detail_view]
    authorize @target
    respond_to do |format|
        format.js
    end
  end

  def update
    @target = @evaluation.targets.find(params[:target_id])
    @student = @evaluation.study_period.student
    authorize @target
    if @target.update_attributes(target_params)
      respond_to do |format|
        format.html {redirect_to(:controller => :students, :action => :index)}
        format.js {
          if params[:detail_view].present?
            @targets = @evaluation.targets.newest_first
            @charted_targets = @evaluation.targets.newest_first
            render 'targets/update_detail_view'
          else
            render 'targets/update'
          end
        }
      end
    end
  end

  def batch_edit
    @students = batch_edit_current_active_student_query
    @list_data = {language: params[:language], group: params[:group]}
    authorize @students
  end

  private

  def target_params
    params.require(:target).permit(:description, :date, :letter_grade, :student_input)
  end

  def find_evaluation
    if params[:evaluation_id]
      @evaluation = Evaluation.find(params[:evaluation_id])
    end
  end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/targets/_form.html.erb
<div class="form-group field col-xs-12">
	<div class="">
		<%= f.label(:date, "Date of entry")%>
		<%= f.text_field(:date, :class=>"form-control datepicker", id: "") %>
	</div>
	
	<div class="">
		<%= f.label(:description, "Description")%>
		<%= f.text_field(:description, :class=>"form-control", :id=>"description") %>
	</div>
	
	<div class="">
		<%= f.label(:student_input, "Student feedback")%>
		<%= f.text_field(:student_input, :class=>"form-control", :id=>"student_input") %>
	</div>
</div>

<div class="col-xs-12"><%= f.radio_button :letter_grade, "A", :id=>"target_a" %> <%= f.label :letter_grade, "A"%></div>

<div class="col-xs-12"><%= f.radio_button :letter_grade, "B", :id=>"target_b" %> <%= f.label :letter_grade, "B"%></div>

<div class="col-xs-12"><%= f.radio_button :letter_grade, "C", :id=>"target_c" %> <%= f.label :letter_grade, "C"%></div>
<div class="col-xs-12"><label for="target[letter_grade]" class="error" style="display:none;">Please choose one.</label></div>

app/views/targets/_target_list.html.erb
<div class="container-fluid section-white margin-top">
	<div class="row" id="margin-top">
		<div class="col-md-12">
		<div class="col-md-5 " id="soft-borders">
			<h3>
				<%= link_to '<i class="glyphicon glyphicon-plus-sign text-success"></i>'.html_safe, 
					'#new_target_modal', 'data-toggle' => 'modal' %>  
				<%= link_to "Daily Targets", targets_path(:evaluation_id=>@evaluation.id) %>	
			</h3>
		</div>
			<div class="col-md-1 col-md-offset-6" >
				
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12" >
			<div class="row">
				<div class="col-wrap white-text margin-sides" id="soft-borders">
					<div class="col-md-4 col text-center" id="soft-borders">
						<h3 id="med">
							Average teacher evaluation in the last 7 recorded targets
						</h3>
						<p id="big">
							<%= @evaluation.target_teacher_eval_week %>
						</p>
					</div>
					<div class="col-md-4 col text-center" id="soft-borders">
						<h3 id="med">
							Average student feedback in the last 7 recorded targets
						</h3>
						<p id="big">
							<%= number_with_precision(@evaluation.target_student_input_week, :precision => 2) %>
						</p>
					</div>
					<div class="col-md-4 col text-center" id="soft-borders">
						<h3 id="med">
							Average grade overall
						</h3>
						<p id="big">
							<%= @evaluation.target_teacher_eval_overall %>
						</p>
					</div>
				</div>
				<div class="col-md-12 target-placehoder">
					<table class="table table-striped" id="soft-borders" >
					<thead>
						<tr>
							<th>
								#
							</th>
							<th>
								First entered
							</th>
							<th>
								Target:
							</th>
							<th class="text-center">
								Student Feedback
							</th>
							<th class="text-center">
								Letter Grade
							</th>
						</tr>
					</thead>
					<tbody>
						<% count = 0 %>
						<% @evaluation.targets.newest_first.limit(10).each do |target| %>
						<tr>
							<td>
                <% if policy(target).update? %>
                    <%= link_to count += 1, edit_target_path(:id => target.id, :evaluation_id=>@evaluation.id), remote: true%>
                <% else %>
                    <%= count += 1 %>
                <% end %>
							</td>
							<td>
								<% unless target.letter_grade.nil? %>
                    <% if policy(target).update? %>
                        <%= link_to (l target.created_at, :format => :short), edit_target_path(:id => target.id, :evaluation_id=>@evaluation.id), remote: true%>
                    <% else %>
                        <%= l target.created_at, :format => :short %>
                    <% end %>
								<% end %>
							</td>
							<td>
                <% if policy(target).update? %>
                    <%= link_to target.description, edit_target_path(:id => target.id, :evaluation_id=>@evaluation.id), remote: true%>
                <% else %>
                    <%= target.description %>
                <% end %>
							</td>
							<td class="text-center">
                <% if policy(target).update? %>
                    <%= link_to target.student_input, edit_target_path(:id => target.id, :evaluation_id=>@evaluation.id), remote: true%>
                <% else %>
                    <%= target.student_input %>
                <% end %>
							</td>
							<td class="text-center">
								<% unless target.letter_grade.nil? %>
                    <% if policy(target).update? %>
                        <%= link_to target.letter_grade, edit_target_path(:id => target.id, :evaluation_id=>@evaluation.id), remote: true%>
                    <% else %>
                        <%= target.letter_grade %>
                    <% end %>
                <% end %>
							</td>
						</tr>
						<% end %>
					</tbody>
				</table>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/targets/_target_list_edit.html.erb
<div class="modal-dialog modal-lg">
	<div class="modal-content">
	  <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	    <h4 class="modal-title" id="myModalLabel">Edit Target</h4>
	  </div>
	  <div class="modal-body">
	  <%= form_for(:target, :url => target_path(:evaluation_id => @evaluation.id, :target_id => @target.id, detail_view: @detail_view), remote:true, :html => {:method => :put, :id =>"edit_target_form"}) do |f| %>
	    <div class="form-group field col-xs-12">
	<div class="">
		<%= f.label(:date, "Date of entry")%>
		<%= f.text_field(:date, :class=>"form-control datepicker", :id=>"") %>
	</div>

	<div class="">
		<%= f.label(:description, "Description")%>
		<%= f.text_field(:description, :class=>"form-control", :id=>"description") %>
	</div>

	<div class="">
		<%= f.label(:student_input, "Student feedback")%>
		<%= f.text_field(:student_input, :class=>"form-control", :id=>"student_input") %>
	</div>
</div>

<div class="col-xs-12"><%= f.radio_button :letter_grade, "A", :id=>"target_a" %> <%= f.label :letter_grade, "A"%></div>

<div class="col-xs-12"><%= f.radio_button :letter_grade, "B", :id=>"target_b" %> <%= f.label :letter_grade, "B"%></div>

<div class="col-xs-12"><%= f.radio_button :letter_grade, "C", :id=>"target_c" %> <%= f.label :letter_grade, "C"%></div>


	  </div>
	  <div class="modal-footer">
	    <%= submit_tag("Save Daily Target", :class => 'btn btn-success', :id=>"update_target") %>
	  </div>
	  <% end %>
	</div>
</div>

app/views/targets/_target_row.html.erb
<td>
  <%= (l target.created_at.to_date, :format => :long) %>
</td>
<td>
  <%= (l target.date, :format => :long) %>
</td>
<td>
  <%= target.description %>
</td>
<td>
  <%= target.letter_grade %>
</td>
<td>
  <%= target.student_input %>
</td>
<td>
<% if policy(:target).edit? %>
  <div class="col-md-12">
    <%= link_to "Edit", edit_target_path(:id => target.id, :evaluation_id=>@evaluation.id, detail_view: 1),
                remote: true, class: "btn btn-default link-justify-absence", title: t('justify_absence'), 'data-toggle' => 'tooltip', 'data-placement' => 'top' %>

  </div>
<% end %>
</td>
<div class="modal fade" id="edit_target_modal_<%= target.evaluation.study_period.student.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Edit Target</h4>
      </div>
    </div>
  </div>
</div>

app/views/targets/_target_table.html.erb
<td class="center-vertically-table-cell empty-table-cell"><%= student.complete_name_cap %></td>
<% if student.latest_target.blank? %>
    <td class="center-vertically-table-cell empty-table-cell empty-td">
      No targets recorded
    </td>
    <td class="empty-table-cell empty-td">
    </td>
    <td class="empty-table-cell empty-td">
    </td>
    <td class="empty-table-cell empty-td">
    </td>
<% else %>
    <td class="center-vertically-table-cell empty-td">
      <% unless student.latest_target.letter_grade.nil? %>
          <% if policy(student.latest_target).update? %>
              <%= link_to (l student.latest_target.created_at, :format => :short), edit_target_path(:id => student.latest_target.id, :evaluation_id=>student.latest_evaluation.id), remote: true%>
          <% else %>
              <%= l student.latest_target.created_at, :format => :short %>
          <% end %>
      <% end %>
    </td>
    <td class="center-vertically-table-cell empty-td">
      <% if policy(student.latest_target).update? %>
          <%= link_to student.latest_target.description, edit_target_path(:id => student.latest_target.id, :evaluation_id=>student.latest_evaluation.id), remote: true%>
      <% else %>
          <%= student.latest_target.description %>
      <% end %>
    </td>
    <td class="center-vertically-table-cell empty-td">
      <% if policy(student.latest_target).update? %>
          <%= link_to student.latest_target.student_input, edit_target_path(:id => student.latest_target.id, :evaluation_id=>student.latest_evaluation.id), remote: true%>
      <% else %>
          <%= student.latest_target.student_input %>
      <% end %>
    </td>
    <td class="center-vertically-table-cell empty-td">
      <% unless student.latest_target.letter_grade.nil? %>
          <% if policy(student.latest_target).update? %>
              <%= link_to student.latest_target.letter_grade, edit_target_path(:id => student.latest_target.id, :evaluation_id=>student.latest_evaluation.id), remote: true%>
          <% else %>
              <%= student.latest_target.letter_grade %>
          <% end %>
      <% end %>
    </td>
<% end %>
<td class="center-vertically-table-cell empty-td">
  <% if student.latest_evaluation.nil? %>
      <row>
        <div class="col-xs-6 text-center no-padding">
          This student does not have an academic profile
        </div>
        <div class="col-xs-6 text-center no-padding">
          <% if policy(student).update? %>
              <%= link_to "Edit this student", student_path(:id => student.id), class: "btn btn-default" %>
          <% end %>
        </div>
      </row>
  <% else %>
      <row>
        <div class="col-xs-6 text-center no-padding">
          <%= link_to 'New target'.html_safe, "#new_target_modal_#{student.id}", 'data-toggle' => 'modal', class: "btn btn-primary" %>
        </div>
        <div class="col-xs-6 text-center no-padding">
          <%= link_to "Target details", targets_path(:evaluation_id=>student.latest_evaluation.id), class: "btn btn-default" %>
        </div>
      </row>
  <% end %>
</td>

app/views/targets/batch_edit.html.erb
<h2 class="batch-table text-center">Targets</h2>

<h3 class="batch-table text-center">List of <%= @list_data[:group].humanize.split.map(&:capitalize).join(' ') %> <%= @list_data[:language].capitalize %> students </h3>

<div>
  <table class="table table-bordered batch-table table-striped" id="soft-borders">
    <thead>
    <tr>
      <th>Student</th>
      <th colspan="4">Latest Target</th>
      <th >Register new Targets</th>
    </tr>
    <tr>
      <th></th>
      <th >Date</th>
      <th >Description</th>
      <th >Student input</th>
      <th >Letter grade</th>
      <th></th>
    </tr>
    </thead>
    <% @students.each do |student| %>
      <tbody>
        <tr id='student_<%= student.id %>'>
          <%= render 'targets/target_table', student: student %>
        </tr>
        <tr>
          <td class="hidden-td">
            <div class="modal fade" id="new_target_modal_<%= student.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Daily Target</h4>
                  </div>
                  <% if student.latest_evaluation.present? %>
                    <div class="modal-body">
                      <%= form_for(:target, :url => targets_path(:evaluation_id => student.latest_evaluation.id), remote:true, :html => {:id=>"target_form_#{student.id}"}) do |f| %>
                        <%= render(:partial => "targets/form", :locals => {:f => f})%>
                        </div>
                        <div class="modal-footer">
                          <%= submit_tag("Add Daily Target", :class => 'btn btn-success') %>
                        </div>
                      <% end %>
                    </div>
                  <% end %>
                  </div>
            </div>
            <div class="modal fade" id="edit_target_modal_<%= student.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Edit Target</h4>
                  </div>
                </div>
              </div>
            </div>
          </td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>

app/views/targets/create.js.erb
<% if @target.errors.any? %>
$('.container').html("<div class=\"alert alert-warning fade in\"><button class=\"close\" data-dismiss=\"alert\">x</button><%= @target.errors.full_messages.join(', ') %></div>\n");
<% else %>
$('.container').html("<div class=\"alert alert-success fade in\"><button class=\"close\" data-dismiss=\"alert\">x</button>Target created successfully for <%= @student.first_name %></div>\n");
<% end %>
$('#student_<%= @student.id %>').html("<%= j render "targets/target_table", student: @student %>")
$('#new_target_modal_<%= @student.id %>').modal('hide')
$('#new_target_modal_<%= @student.id %>').find('form input[type="text"]').val('')

app/views/targets/edit.js.erb
$('#edit_target_modal_<%= @student.id %>').html("<%= j render "targets/target_list_edit" %>")
$('#edit_target_modal_<%= @student.id %>').modal('show')

app/views/targets/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-5 col-center margin-top margin-bottom">
      <ul class="nav nav-tabs nav-justified red" id="margin-top">
        <li class="nav-item pagination-centered text-center" id="">
          <%= link_to "Back to Academic Profile index", evaluations_path(:student_id => @evaluation.study_period.student.id) %>
        </li>
        <li class="nav-item pagination-centered text-center" id="">
          <%= link_to "Back to student Academic Profile", exercises_evaluation_path(:id => @evaluation.id, :student_id => @evaluation.study_period.student.id) %>
        </li>
      </ul>
    </div>
  </div>
	<div class="row">
		<div class="col-md-12">
      <%= link_to 'PDF Report', targets_path(:evaluation_id=>@evaluation.id, :format => :pdf), :class =>'btn btn-danger btn-inverse' %>
			<div class="page-header">
				<h2 class="text-center font-open-sans">
					Daily Target index for <%= @evaluation.study_period.student.first_name%> <%= @evaluation.study_period.student.last_name%>
				</h2>
			</div>
			<div class="row">
				<div class="col-md-7">
					<h3 class="text-center">
						List
					</h3>
					<div class="col-md-12 section-white">
            <div class="col-md-12 margin-bottom-40">
              <h4 class="header4-bottom margin-bottom text-center">
                Targets
              </h4>
            </div>
						<div class="col-md-12 margin-top">
							<table class="table table-striped margin-top" id="target_index_table">
								<thead>
									<tr>
										<th >
											Date created
										</th>
										<th >
											Date assigned
										</th>
										<th >
											Description
										</th>
										<th >
											Letter grade
										</th>
										<th >
											Student Input
										</th>
                    <th >
											Actions
										</th>
									</tr>
								</thead>
								<tbody>
									<% @targets.each do |target| %>
                  <tr id="target_<%= target.id %>">
                    <%= render "target_row",  target: target  %>
  								</tr>
									<% end %>
								</tbody>
							</table>
						</div>
					</div>
				</div>
				<div class="col-md-5">
          <h3 class="text-center">
            Progress Graphs
            <span class="glyphicon glyphicon-plus-sign options-icon" ></span>
          </h3>
          <div class="dropdown dropdown-graph-dates hidden">
            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Dropdown Example
              <span class="caret"></span></button>
            <ul class="dropdown-menu">
              <%= form_tag targets_path(format: :html), method: :get do %>
                  <%= text_field_tag :start_date, '',{id: 'start-date-graph', class: 'div-centered graph-input'} %>
                  <%= text_field_tag :end_date, '' ,{id: 'end-date-graph', class: 'div-centered graph-input'} %>
                  <%= hidden_field_tag :evaluation_id, @evaluation.id %>
                  <div class="text-center">
                    <%= submit_tag 'Update graph', class: 'btn btn-default graph-update-btn' %>
                  </div>
              <% end %>
            </ul>
          </div>
						<div class="col-md-12">
                <div id="target_line_chart" class="section-white margin-bottom">
  								<%= render 'targets/chart_partials/line_chart', charted_targets: @charted_targets %>
  							</div>
							<footer class="col-md-offset-1">
								  <p>Grade: A = 90-100, B = 75-89, C = < 75</p>
								</footer>
                <div id="target_pie_chart" class="section-white margin-top">
  								<%= render 'targets/chart_partials/pie_chart', charted_targets: @charted_targets %>
  							</div>
						</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/targets/index.pdf.erb
<h3 class="text-center font-open-sans">
  Target Report for <%= @evaluation.study_period.student.first_name%> <%= @evaluation.study_period.student.last_name%>
</h3>
            <div class="margin-top">
              <h5 class="text-center">
                Line Chart
              </h5>
              <%= line_chart [{name: "Grade", data: @targets.map{|t| [t.date, human_abc(t.letter_grade)] }},
                              {name: "Student Input", data: @targets.map{|t| [t.date, t.student_input] }}], width: '1230px', height: '195px', library: {vAxis: {
                  viewWindow: {
                      min: 0,
                      max: 105
                  },
                  ticks: [0, 25, 50, 75, 100]}, hAxis: {format: 'dd/MM/yy' }, curveType: 'function', legend: { position: 'right'}} %>
            </div>
            <footer class="col-md-offset-1">
              <p>Grade: A = 90-100, B = 75-89, C = < 75</p>
            </footer>
            <div class="margin-top">
              <h5 class="text-center">
                Pie Chart
              </h5>
              <%= pie_chart @targets.group(:letter_grade).count, width: '1230px', height: '195px', library: {legend: {position: 'bottom', textStyle: {color: 'black', fontSize: 14}},
                                                                           colors: ['#729f98', '#aa863a', '#e6af4b', '#bcd5d1', '#f6c7b6']} %>
            </div>

app/views/targets/update.js.erb
<% if @target.errors.any? %>
$('.container').html("<div class=\"alert alert-warning fade in\"><button class=\"close\" data-dismiss=\"alert\">x</button><%= @target.errors.full_messages.join(', ') %></div>\n");
<% else %>
$('.container').html("<div class=\"alert alert-success fade in\"><button class=\"close\" data-dismiss=\"alert\">x</button>Target updated successfully for <%= @student.first_name %></div>\n");
<% end %>
$('#student_<%= @student.id %>').html("<%= j render "targets/target_table", student: @student %>")
$('#edit_target_modal_<%= @student.id %>').modal('hide')

app/views/targets/update_detail_view.js.erb
$('#target_<%= @target.id %>').html("<%= j render "targets/target_row", target: @target %>")
$('#target_line_chart').html("<%= j render "targets/chart_partials/line_chart", charted_targets: @charted_targets %>")
$('#target_pie_chart').html("<%= j render "targets/chart_partials/pie_chart", charted_targets: @charted_targets %>")
$('#edit_target_modal_<%= @student.id %>').modal('hide')