config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
      :sessions => "users/sessions",
      :registrations => "users/registrations" }
  root to: "public#index"

  match 'admin/academic' => 'admin#academic', :via => :get
  match 'admin/pdf' => 'admin#pdf', :via => :get

  resources :users do
    member do
      get :delete
    end
  end

  resources :fixed_duration_programs do
    member do
      get :delete
    end
  end

  resources :insurances do
    member do
      get :update_insurance_cost
    end
  end

  resources :notes do
    member do
      get :delete
    end
  end

  resources :statements do
    member do
      get :delete
    end
  end

  resources :digital_tests do
    member do
      get :delete
    end
  end

  resources :admin do
    collection do
      get :academic
    end
    member do
      get :delete
    end
  end

  resources :payments do
    member do
      get :delete
    end
  end

  resources :invoices do
    member do
      get :load_config
      get :delete
    end
  end

  resources :agencies do
    member do
      get :delete
    end
  end

  resources :promos do
    member do
      get :delete
    end
  end

  resources :regions do

    member do
      get :delete
    end
  end

  resources :accommodations do
    member do
      get :delete
    end
  end

  resources :hours do
    member do
      get :delete
    end
  end
  
  resources :special_activities do
    member do
      get :delete
    end
  end
  
  resources :programs do
    member do
      get :delete
    end
  end
  
  resources :tests do
    member do
      get :delete
    end
  end
  
  resources :quizzes do
    member do
      get :delete
    end
  end
  
  resources :students do
    collection do
      post :import
      get :edit_multiple
      get :active
      get :student_list
      put :update_multiple
      patch :activate
      patch :deactivate
    end

    member do
      get :delete
    end

    resources :study_periods do
      member do
        get :letter_of_acceptance
        get :delete
      end
    end

    resources :quotes do
      member do
        get :load_config
        get :delete
      end
    end

    resources :pro_formas do
      member do
        get :load_config
        get :delete
      end
    end

    resources :invoices do
      member do
        get :delete
      end
    end
  end
  
  resources :attendances do
    member do
      get :delete
      patch :justify_absence
    end
  end
  
  resources :targets do
    member do
      get :delete
    end
  end
  
  resources :evaluations do
    member do
      get :report
      get :delete
      get :exercises
      get :daily
      get :regular
      put :set_evaluation_to_active
    end
  end

  resources :sharp_and_smarts do
    member do
      get :delete
    end
  end

  resources :automatizations do
    member do
      get :delete
    end
  end
  
  resources :items do
    member do
      get :delete
    end
  end

  
  resources :quotes, only: [:index]
  
  resources :pro_formas, only: [:index]
  
  resources :invoices, only: :index

  match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]

  match "/course/" => "public#language", via: :get, :as => :course_language

  match "/course/:language" => "public#group", via: :get, :as => :course_language_group

  match "/course/:language/group/:group" => "public#type", via: :get, :as => :course_language_group_type

  match "/course/:language/group/:group/type/attendances/" => "attendances#batch_edit", via: :get, :as => :course_language_group_type_attendances

  match "/course/:language/group/:group/type/targets/" => "targets#batch_edit", via: :get, :as => :course_language_group_type_targets

  match "/course/:language/group/:group/type/sharp_and_smarts/" => "sharp_and_smarts#batch_edit", via: :get, :as => :course_language_group_type_sharp_and_smarts

  match "/course/:language/group/:group/type/automatizations/" => "automatizations#batch_edit", via: :get, :as => :course_language_group_type_automatizations

end

app/models/insurance.rb
class Insurance < ActiveRecord::Base

  has_many :study_periods
  has_many :statements

  validates_presence_of :name
  validates_numericality_of :cost
end

app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController

  before_action :authenticate_user!

  def index
    @insurances = Insurance.all
    authorize @insurances
  end

  def edit
    @insurance = Insurance.find(params[:id])
    authorize @insurance
  end

  def update
    @insurance = Insurance.find(params[:id])
    authorize @insurance
    if @insurance.update_attributes(insurance_params)
      flash[:success] = 'Insurance record successfully updated'
      redirect_to(insurances_path)
    else
      flash[:error] = 'Insurance record could not be updated'
      render("edit")
    end
  end

  def new
    @insurance = Insurance.new
    authorize @insurance
  end

  def create
    @insurance = Insurance.new(insurance_params)
    authorize @insurance
    if @insurance.save
      flash[:success] = 'Insurance record successfully created'
      redirect_to(insurances_path)
    else
      flash[:error] = 'Insurance record could not be created'
      render("new")
    end
  end

  def destroy
    @insurance = Insurance.find(params[:id])
    authorize @insurance
    if @insurance.destroy
      flash[:success] = 'Insurance record successfully deleted'
      redirect_to(insurances_path)
    else
      flash[:error] = 'Insurance record could not be deleted'
      render("delete")
    end
  end

  def update_insurance_cost
    @insurance = Insurance.find(params[:id])
    @billing_type = params[:billing_type]
    authorize @insurance
    respond_to do |format|
      format.js
    end
  end

  private

  def insurance_params
    params.require(:insurance).permit(:name, :cost)
  end
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/views/insurances/_form.html.erb
<div class="form-group">
  <%= f.label(:name, "Name of Insurance")%>
  <%= f.text_field(:name, :class=>"form-control") %>
</div>

<div class="form-group">
  <%= f.label(:cost, "Cost per week")%>
  <%= f.text_field(:cost, :class=>"form-control") %>
</div>

app/views/insurances/_insurance_option.html.erb
<option value="<%= @insurance.cost %>"><%= @insurance.cost %></option>

app/views/insurances/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 col-center margin-top margin-bottom">
      <ul class="nav nav-tabs nav-justified red" id="margin-top">
        <li class="nav-item pagination-centered text-center" id="">
          <%= link_to "Create promotion", new_promo_path%>
        </li>
        <li>
          <%= link_to "Insurance index", promos_path %>
        </li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h3 class="text-center">
        Edit insurance
      </h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12" id="margin-bottom">
      <%= form_for(@insurance, :url => insurance_path, :html => {:method => :put}) do |f| %>

          <%= render(:partial => "form", :locals => {:f => f})%>

          <%= submit_tag("Save insurance", :class => 'btn btn-success', :id=>"margin-top")%>

      <% end %>
    </div>
  </div>
</div>

app/views/insurances/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h3 class="text-center">
        Insurance Index
      </h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 col-center margin-top margin-bottom">
      <ul class="nav nav-tabs nav-justified red" id="margin-top">
        <li class="nav-item pagination-centered text-center" id="">
          <%= link_to "Create insurance", new_insurance_path %>
        </li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 section-white"  id="student-panel">
      <h3 class="header3-bottom margin-bottom">
        List of Insurance
      </h3>
      <table class="table responsive no-wrap table-stu table-striped table-responsive table-hover margin-top" id="program_table">
        <thead>
        <tr>
          <th>
            #
          </th>
          <th>
            Name
          </th>
          <th>
            Cost
          </th>
          <th>
            Actions
          </th>
        </tr>
        </thead>
        <tbody>
        <% @count = 0 %>
        <% @insurances.each do |insurance|%>
            <tr>
              <td>
                <%= @count += 1 %>
              </td>
              <td>
                <%= insurance.name %>
              </td>
              <td>
                <%= insurance.cost %>
              </td>
              <td>
                <%= link_to "Edit Insurance", edit_insurance_path(insurance.id) %>

                <%= link_to "Delete insurance", insurance_path(insurance.id), method: 'delete' %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/insurances/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2 col-center margin-top margin-bottom">
      <ul class="nav nav-tabs nav-justified red" id="margin-top">
        <li>
          <%= link_to "Insurance index", insurances_path %>
        </li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h3 class="text-center">
        Add new Insurance
      </h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@insurance, :url => insurances_path) do |f| %>

          <%= render(:partial => "form", :locals => {:f => f})%>

          <%= submit_tag("Add insurance", :class => 'btn btn-success')%>

      <% end %>
    </div>
  </div>
</div>