config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
      :sessions => "users/sessions",
      :registrations => "users/registrations" }
  root to: "public#index"

  match 'admin/academic' => 'admin#academic', :via => :get
  match 'admin/pdf' => 'admin#pdf', :via => :get

  resources :users do
    member do
      get :delete
    end
  end

  resources :fixed_duration_programs do
    member do
      get :delete
    end
  end

  resources :insurances do
    member do
      get :update_insurance_cost
    end
  end

  resources :notes do
    member do
      get :delete
    end
  end

  resources :statements do
    member do
      get :delete
    end
  end

  resources :digital_tests do
    member do
      get :delete
    end
  end

  resources :admin do
    collection do
      get :academic
    end
    member do
      get :delete
    end
  end

  resources :payments do
    member do
      get :delete
    end
  end

  resources :invoices do
    member do
      get :load_config
      get :delete
    end
  end

  resources :agencies do
    member do
      get :delete
    end
  end

  resources :promos do
    member do
      get :delete
    end
  end

  resources :regions do

    member do
      get :delete
    end
  end

  resources :accommodations do
    member do
      get :delete
    end
  end

  resources :hours do
    member do
      get :delete
    end
  end
  
  resources :special_activities do
    member do
      get :delete
    end
  end
  
  resources :programs do
    member do
      get :delete
    end
  end
  
  resources :tests do
    member do
      get :delete
    end
  end
  
  resources :quizzes do
    member do
      get :delete
    end
  end
  
  resources :students do
    collection do
      post :import
      get :edit_multiple
      get :active
      get :student_list
      put :update_multiple
      patch :activate
      patch :deactivate
    end

    member do
      get :delete
    end

    resources :study_periods do
      member do
        get :letter_of_acceptance
        get :delete
      end
    end

    resources :quotes do
      member do
        get :load_config
        get :delete
      end
    end

    resources :pro_formas do
      member do
        get :load_config
        get :delete
      end
    end

    resources :invoices do
      member do
        get :delete
      end
    end
  end
  
  resources :attendances do
    member do
      get :delete
      patch :justify_absence
    end
  end
  
  resources :targets do
    member do
      get :delete
    end
  end
  
  resources :evaluations do
    member do
      get :report
      get :delete
      get :exercises
      get :daily
      get :regular
      put :set_evaluation_to_active
    end
  end

  resources :sharp_and_smarts do
    member do
      get :delete
    end
  end

  resources :automatizations do
    member do
      get :delete
    end
  end
  
  resources :items do
    member do
      get :delete
    end
  end

  
  resources :quotes, only: [:index]
  
  resources :pro_formas, only: [:index]
  
  resources :invoices, only: :index

  match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]

  match "/course/" => "public#language", via: :get, :as => :course_language

  match "/course/:language" => "public#group", via: :get, :as => :course_language_group

  match "/course/:language/group/:group" => "public#type", via: :get, :as => :course_language_group_type

  match "/course/:language/group/:group/type/attendances/" => "attendances#batch_edit", via: :get, :as => :course_language_group_type_attendances

  match "/course/:language/group/:group/type/targets/" => "targets#batch_edit", via: :get, :as => :course_language_group_type_targets

  match "/course/:language/group/:group/type/sharp_and_smarts/" => "sharp_and_smarts#batch_edit", via: :get, :as => :course_language_group_type_sharp_and_smarts

  match "/course/:language/group/:group/type/automatizations/" => "automatizations#batch_edit", via: :get, :as => :course_language_group_type_automatizations

end

app/models/special_activity.rb
class SpecialActivity < ActiveRecord::Base
  belongs_to :evaluation

  validates_presence_of :date

  scope :newest_first, lambda { order("special_activities.created_at DESC" )}

  validate :is_evaluation_active, :on => [:create, :update, :edit, :delete, :destroy]

  def is_evaluation_active
    unless evaluation.is_active?
      errors[:base] << 'The academic profile to which this attendance belongs must be active'
    end
  end
end

app/controllers/special_activities_controller.rb
class SpecialActivitiesController < ApplicationController

  before_action :authenticate_user!
  before_action :find_evaluation
  
  def index
    if params[:evaluation_id]
      @special_activities = @evaluation.special_activities.newest_first
    else
      @special_activities = SpecialActivity.newest_first
    end
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "special_activities.pdf",
               :template => "special_activities/index.pdf.erb",
               :layout => "pdf_layout.html",
               :page_size => "Letter",
               :orientation => 'Landscape',
               :javascript_delay => 3000,
               margin:  {   top:               5,                     # default 10 (mm)
                            bottom:            5,
                            left:              10,
                            right:             10 }
      end
    end
    authorize @special_activities
  end

  def show
    if params[:evaluation_id]
      @special_activity = @evaluation.special_activities.find(:id)
    else
      @special_activity = SpecialActivity.find(params[:id])
    end
    authorize @special_activity
  end

  def new
    if params[:evaluation_id]
      @special_activity = @evaluation.special_activities.new(special_activity_params)
    else
      @special_activity = SpecialActivity.new(special_activity_params)
    end
    authorize @special_activity
  end
  
  def create
    if params[:evaluation_id]
      @special_activity = @evaluation.special_activities.new(special_activity_params)
    else
      @special_activity = SpecialActivity.new(special_activity_params)
    end
    authorize @special_activity
    if @special_activity.save
      respond_to do |format|
        format.html {redirect_to(:controller => :students, :action => :index)}
        format.js 
      end
    end
  end

  def edit
    if params[:evaluation_id]
      @special_activity = @evaluation.special_activities.find(params[:id])
    else
      @special_activity = SpecialActivity.find(params[:id])
    end
    authorize @special_activity
    respond_to do |format|
        format.js 
    end
  end
  
  def update
    if params[:evaluation_id]
      @special_activity = @evaluation.special_activities.find(params[:id])
    else
      @special_activity = SpecialActivity.find(params[:id])
    end
    authorize @special_activity
    if @special_activity.update_attributes(special_activity_params)
      respond_to do |format|
        format.html {redirect_to(:controller => :students, :action => :index)}
        format.js 
      end
    end
  end
  

  def delete
    if params[:evaluation_id]
      @special_activity = @evaluation.special_activities.find(:id)
    else
      @special_activity = SpecialActivity.find(params[:id])
    end
    authorize @special_activity
  end
  
  def destroy
    if params[:evaluation_id]
      @special_activity = @evaluation.special_activities.find(:id)
    else
      @special_activity = SpecialActivity.find(params[:id])
    end
    authorize @special_activity
    if @special_activity.destroy
      redirect_to(:controller => :students, :action => :index)
    end
  end
  
  private
  
  def special_activity_params
    params.require(:special_activity).permit(:description, :date, :research_grade, 
      :presentation_grade, :written_grade, :letter_grade)
  end
  
  def find_evaluation
    if params[:evaluation_id]
      @evaluation = Evaluation.find(params[:evaluation_id])
    end
  end
end

app/helpers/special_activities_helper.rb
module SpecialActivitiesHelper
end

app/views/special_activities/_edit_form.html.erb
<div class="form-group field col-xs-12">
	<div class="">
		<%= f.label(:date, "Date of entry")%>
		<%= f.text_field(:date, :class=>"form-control", :id=>"sa_edit_date") %>
	</div>
	
	<div class="">
		<%= f.label(:description, "Description")%>
		<%= f.text_field(:description, :class=>"form-control", :id=>"sa_description") %>
	</div>
</div>

<div class="col-xs-3">Research</div>

<div class="col-xs-3"><%= f.radio_button :research_grade, "A", :id=>"sar_a" %> <%= f.label :research, "A"%></div>

<div class="col-xs-3"><%= f.radio_button :research_grade, "B", :id=>"sar_b" %> <%= f.label :research, "B"%></div>

<div class="col-xs-3"><%= f.radio_button :research_grade, "C", :id=>"sar_c" %> <%= f.label :research, "C"%></div>
<div class="col-xs-12"><label for="special_activity[research_grade]" class="error" style="display:none;">Please choose one.</label></div>

<div class="col-xs-3">Presentation</div>

<div class="col-xs-3"><%= f.radio_button :presentation_grade, "A", :id=>"sap_a" %> <%= f.label :presentation, "A"%></div>

<div class="col-xs-3"><%= f.radio_button :presentation_grade, "B", :id=>"sap_b" %> <%= f.label :presentation, "B"%></div>

<div class="col-xs-3"><%= f.radio_button :presentation_grade, "C", :id=>"sap_c" %> <%= f.label :presentation, "C"%></div>
<div class="col-xs-12"><label for="special_activity[presentation_grade]" class="error" style="display:none;">Please choose one.</label></div>
<div class="col-xs-3">Written</div>

<div class="col-xs-3"><%= f.radio_button :written_grade, "A", :id=>"saw_a" %> <%= f.label :written, "A"%></div>

<div class="col-xs-3"><%= f.radio_button :written_grade, "B", :id=>"saw_b" %> <%= f.label :written, "B"%></div>

<div class="col-xs-3"><%= f.radio_button :written_grade, "C", :id=>"saw_c" %> <%= f.label :written, "C"%></div>
<div class="col-xs-12"><label for="special_activity[written_grade]" class="error" style="display:none;">Please choose one.</label></div>
<div class="col-xs-3">Overall</div>

<div class="col-xs-3"><%= f.radio_button :letter_grade, "A", :id=>"sa_a" %> <%= f.label :letter_grade, "A"%></div>

<div class="col-xs-3"><%= f.radio_button :letter_grade, "B", :id=>"sa_b" %> <%= f.label :letter_grade, "B"%></div>

<div class="col-xs-3"><%= f.radio_button :letter_grade, "C", :id=>"sa_c" %> <%= f.label :letter_grade, "C"%></div>
<div class="col-xs-12"><label for="special_activity[letter_grade]" class="error" style="display:none;">Please choose one.</label></div>

app/views/special_activities/_form.html.erb
<div class="form-group field col-xs-12">
	<div class="">
		<%= f.label(:date, "Date of entry")%>
		<%= f.text_field(:date, :class=>"form-control", :id=>"sa_date") %>	
	</div>
	
	<div class="">
		<%= f.label(:description, "Description")%>
		<%= f.text_field(:description, :class=>"form-control", :id=>"sa_description") %>
	</div>
</div>

<div class="col-xs-3">Research</div>

<div class="col-xs-3"><%= f.radio_button :research_grade, "A", :id=>"sar_a" %> <%= f.label :research, "A"%></div>

<div class="col-xs-3"><%= f.radio_button :research_grade, "B", :id=>"sar_b" %> <%= f.label :research, "B"%></div>

<div class="col-xs-3"><%= f.radio_button :research_grade, "C", :id=>"sar_c" %> <%= f.label :research, "C"%></div>
<div class="col-xs-12"><label for="special_activity[research_grade]" class="error" style="display:none;">Please choose one.</label></div>

<div class="col-xs-3">Presentation</div>

<div class="col-xs-3"><%= f.radio_button :presentation_grade, "A", :id=>"sap_a" %> <%= f.label :presentation, "A"%></div>

<div class="col-xs-3"><%= f.radio_button :presentation_grade, "B", :id=>"sap_b" %> <%= f.label :presentation, "B"%></div>

<div class="col-xs-3"><%= f.radio_button :presentation_grade, "C", :id=>"sap_c" %> <%= f.label :presentation, "C"%></div>
<div class="col-xs-12"><label for="special_activity[presentation_grade]" class="error" style="display:none;">Please choose one.</label></div>
<div class="col-xs-3">Written</div>

<div class="col-xs-3"><%= f.radio_button :written_grade, "A", :id=>"saw_a" %> <%= f.label :written, "A"%></div>

<div class="col-xs-3"><%= f.radio_button :written_grade, "B", :id=>"saw_b" %> <%= f.label :written, "B"%></div>

<div class="col-xs-3"><%= f.radio_button :written_grade, "C", :id=>"saw_c" %> <%= f.label :written, "C"%></div>
<div class="col-xs-12"><label for="special_activity[written_grade]" class="error" style="display:none;">Please choose one.</label></div>
<div class="col-xs-3">Overall</div>

<div class="col-xs-3"><%= f.radio_button :letter_grade, "A", :id=>"sa_a" %> <%= f.label :letter_grade, "A"%></div>

<div class="col-xs-3"><%= f.radio_button :letter_grade, "B", :id=>"sa_b" %> <%= f.label :letter_grade, "B"%></div>

<div class="col-xs-3"><%= f.radio_button :letter_grade, "C", :id=>"sa_c" %> <%= f.label :letter_grade, "C"%></div>
<div class="col-xs-12"><label for="special_activity[letter_grade]" class="error" style="display:none;">Please choose one.</label></div>

app/views/special_activities/_special_activity_list.html.erb
<div class="container-fluid section-white margin-top">
	<div class="row" id="margin-top">
		<div class="col-md-12">
			<div class="col-md-9" id="soft-borders">
				<h3><%= link_to '<i class="glyphicon glyphicon-plus-sign text-success"></i>'.html_safe, '#new_activity_modal', 'data-toggle' => 'modal' %>
					<%= link_to "Special Activity", special_activities_path(:evaluation_id=>@evaluation.id) %>
				</h3>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12" >
			<div class="row">
				<div class="col-wrap white-text margin-sides" id="soft-borders">
					<div class="col-md-12 col text-center" id="soft-borders">
						<h3 id="med">
							Average Special Activity letter grade in the last 2 months
						</h3>
						<p id="big">
							<%= @evaluation.special_activity_average_letter_grade_bimonthly %>
						</p>
					</div>
				</div>
				<div class="col-md-12">
					<table class="table table-striped" id="soft-borders" >
					<thead>
						<tr>
							<th>
								#
							</th>
							<th>
								Date:
							</th>
							<th>
								Overall Grade
							</th>
							<th>
								Description
							</th>
						</tr>
					</thead>
					<tbody>
						<% count = 0 %>
						<% @evaluation.special_activities.newest_first.limit(10).each do |sa| %>
						<tr>
							<td>
                <% if policy(sa).update? %>
                    <%= link_to count += 1, edit_special_activity_path(:id => sa.id, :evaluation_id=>@evaluation.id), remote: true%>
                <% else %>
                  <%= count += 1 %>
                <% end %>
							</td>
							<td>
                <% if policy(sa).update? %>
                    <%= link_to (l sa.date, :format => :long), edit_special_activity_path(:id => sa.id, :evaluation_id=>@evaluation.id), remote: true%>
                <% else %>
                    <%= l sa.date, :format => :long %>
                <% end %>
							</td>
							<td>
								<% if sa.letter_grade.nil? %>
                    'Not yet assigned'
								<% else %>
                    <% if policy(sa).update? %>
                        <%= link_to sa.letter_grade, edit_special_activity_path(:id => sa.id, :evaluation_id=>@evaluation.id), remote: true%>
                    <% else %>
                        <%= sa.letter_grade %>
                    <% end %>
								<% end %>
							</td>
							<td>
                <% if policy(sa).update? %>
                    <%= link_to sa.description, edit_special_activity_path(:id => sa.id, :evaluation_id=>@evaluation.id), remote: true%>
                <% else %>
                    <%= sa.description %>
                <% end %>
							</td>
						</tr>
						<% end %>
					</tbody>
				</table>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/special_activities/_special_activity_list_edit.html.erb
<div class="modal-dialog modal-lg">
	<div class="modal-content">
		  <div class="modal-header">
		    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		    <h4 class="modal-title" id="myModalLabel">Edit Special Activity</h4>
		  </div>
		  <div class="modal-body">
	      	<%= form_for(:special_activity, :url => special_activity_path(:evaluation_id => @evaluation.id), remote:true, :html => {:method => :put, :id =>"edit_special_activity_form"}) do |f| %>
	        	<%= render(:partial => "special_activities/edit_form", :locals => {:f => f})%>
	      </div>
	      <div class="modal-footer">
	        <%= submit_tag("Edit Special Activity", :class => 'btn btn-success', :id=>"update_special_activity") %>
	      </div>
	      <% end %>
	</div>
</div>

app/views/special_activities/create.js.erb
<% if @special_activity.errors.any? %>
$('.container').html("<div class=\"alert alert-warning fade in\"><button class=\"close\" data-dismiss=\"alert\">x</button><%= @special_activity.errors.full_messages.join(', ') %></div>\n");
<% else %>
$('.container').html("<div class=\"alert alert-success fade in\"><button class=\"close\" data-dismiss=\"alert\">x</button>Special Activity created successfully</div>\n");
<% end %>
$('.special_activities').html("<%= j render "special_activities/special_activity_list" %>")
$('#new_activity_modal').modal('hide')
$('#new_activity_modal').find('form input[type="text"]').val('')

app/views/special_activities/delete.html.erb
<h1>SpecialActivities#delete</h1>
<p>Find me in app/views/special_activities/delete.html.erb</p>

app/views/special_activities/edit.html.erb
<h1>SpecialActivities#edit</h1>
<p>Find me in app/views/special_activities/edit.html.erb</p>

app/views/special_activities/edit.js.erb
$('#edit_activity_modal').html("<%= j render "special_activities/special_activity_list_edit", locals: { items: @selected } %>")
$('#edit_activity_modal').modal('show')

app/views/special_activities/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-5 col-center margin-top margin-bottom">
      <ul class="nav nav-tabs nav-justified red" id="margin-top">
        <li class="nav-item pagination-centered text-center" id="">
          <%= link_to "Back to Academic Profile index", evaluations_path(:student_id => @evaluation.study_period.student.id) %>
        </li>
        <li class="nav-item pagination-centered text-center" id="">
          <%= link_to "Back to student Academic Profile", exercises_evaluation_path(:id => @evaluation.id, :student_id => @evaluation.study_period.student.id) %>
        </li>
      </ul>
    </div>
  </div>
	<div class="row">
		<div class="col-md-12">
      <%= link_to 'PDF Report', special_activities_path(:evaluation_id=>@evaluation.id, :format => :pdf), :class =>'btn btn-danger btn-inverse' %>
			<div class="page-header">
				<h2 class="text-center font-open-sans">
					Special Activity index for <%= @evaluation.study_period.student.first_name%> <%= @evaluation.study_period.student.last_name%>
				</h2>
			</div>
			<div class="row">
				<div class="col-md-7">
					<h3 class="text-center">
						List
					</h3>
					<div class="col-md-12 section-white">
            <div class="col-md-12 margin-bottom-40">
              <h4 class="header4-bottom text-center">
                Special Activities
              </h4>
            </div>
						<div class="col-md-12 margin-top">
							<table class="table table-striped margin-top" id="sa_index_table">
								<thead>
									<tr>
										<th>
											#
										</th>
										<th >
											Date
										</th>
										<th >
											Description
										</th>
										<th >
											Research grade
										</th>
										<th >
											Presentation grade
										</th>
										<th >
											Written grade
										</th>
										<th >
											Overall grade
										</th>
									</tr>
								</thead>
								<tbody>
									<% count = 0 %>
									<% @special_activities.each do |sa| %>
									<tr>
										<td>
											<%= count += 1 %>
										</td>
										<td>
											<%= (l sa.date, :format => :long) %>
										</td>
										<td>
											<%= sa.description %>
										</td>
										<td>
											<%= sa.research_grade %>
										</td>
										<td>
											<%= sa.presentation_grade %>
										</td>
										<td>
											<%= sa.written_grade %>
										</td>
										<td>
											<%= sa.letter_grade %>
										</td>
									</tr>
									<% end %>
								</tbody>
							</table>
						</div>
					</div>
				</div>
				<div class="col-md-5">
					<h3 class="text-center">
						Progress Graphs
					</h3>
						<div class="col-md-12">
							<div class="section-white margin-bottom">
								<h4 class="text-center header4-bottom">
									Line Chart
								</h4>
								<%= line_chart [{name: "Overall", data: @special_activities.limit(15).map{|t| [t.date, human_abc(t.letter_grade)] }},
								{name: "Research", data: @special_activities.limit(15).map{|t| [t.date, human_abc(t.research_grade)] }},
								{name: "Presentation", data: @special_activities.limit(15).map{|t| [t.date, human_abc(t.presentation_grade)] }},
								{name: "Written", data: @special_activities.limit(15).map{|t| [t.date, human_abc(t.written_grade)] }}], library: {vAxis: {
                    viewWindow: {
                        min: 0,
                        max: 105
                    },
                    ticks: [0, 25, 50, 75, 100]}, hAxis: {format: 'dd/MM/yy' }, curveType: 'function', legend: { position: 'right'}} %>
							</div>
							<div class="section-white margin-top">
								<h4 class="text-center header4-bottom">
									Pie Chart
								</h4>
								<%= pie_chart @special_activities.group(:letter_grade).count, library: {legend: {position: 'bottom', textStyle: {color: 'black', fontSize: 14}}, 
								colors: ['#729f98', '#aa863a', '#e6af4b', '#bcd5d1', '#f6c7b6'], title: "Overall Grade"} %>
							</div>
						</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/special_activities/index.pdf.erb
<h3 class="text-center font-open-sans">
  Special Activity Report for <%= @evaluation.study_period.student.first_name%> <%= @evaluation.study_period.student.last_name%>
</h3>
            <div class="margin-bottom">
              <h5 class="text-center">
                Line Chart
              </h5>
              <%= line_chart [{name: "Overall", data: @special_activities.map{|t| [t.date, human_abc(t.letter_grade)] }},
                              {name: "Research", data: @special_activities.map{|t| [t.date, human_abc(t.research_grade)] }},
                              {name: "Presentation", data: @special_activities.map{|t| [t.date, human_abc(t.presentation_grade)] }},
                              {name: "Written", data: @special_activities.map{|t| [t.date, human_abc(t.written_grade)] }}], width: '1230px', height: '290px', library: {vAxis: {
                  viewWindow: {
                      min: 0,
                      max: 105
                  },
                  ticks: [0, 25, 50, 75, 100]}, hAxis: {format: 'dd/MM/yy' }, curveType: 'function', legend: { position: 'right'}} %>
            </div>
            <div class="margin-top">
              <h5 class="text-center">
                Pie Chart
              </h5>
              <%= pie_chart @special_activities.group(:letter_grade).count,width: '1230px', height: '290px', library: {legend: {position: 'bottom', textStyle: {color: 'black', fontSize: 14}},
                                                                                      colors: ['#729f98', '#aa863a', '#e6af4b', '#bcd5d1', '#f6c7b6'], title: "Overall Grade"} %>
            </div>

app/views/special_activities/new.html.erb
<h1>SpecialActivities#new</h1>
<p>Find me in app/views/special_activities/new.html.erb</p>

app/views/special_activities/show.html.erb
<h1>SpecialActivities#show</h1>
<p>Find me in app/views/special_activities/show.html.erb</p>

app/views/special_activities/update.js.erb
<% if @special_activity.errors.any? %>
$('.container').html("<div class=\"alert alert-warning fade in\"><button class=\"close\" data-dismiss=\"alert\">x</button><%= @special_activity.errors.full_messages.join(', ') %></div>\n");
<% else %>
$('.container').html("<div class=\"alert alert-success fade in\"><button class=\"close\" data-dismiss=\"alert\">x</button>Special Activity updated successfully for <%= @student.first_name %></div>\n");
<% end %>
$('.special_activities').html("<%= j render "special_activities/special_activity_list" %>")
$('#edit_activity_modal').modal('hide')